# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-10-25T04:31:21Z"
  labels:
    app: simplebank
  name: simplebank
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: POSTGRES_DB
      value: bankdb
    image: docker.io/library/postgres:latest
    name: postgres
    ports:
    - containerPort: 3000
      hostPort: 3000
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: ccf228333faf5ae173ecc9df3001ce81b47901d9452e188577533170f1efa8d0-pvc
  - image: localhost/simplebank-api:latest
    name: simplebank-api
  volumes:
  - name: ccf228333faf5ae173ecc9df3001ce81b47901d9452e188577533170f1efa8d0-pvc
    persistentVolumeClaim:
      claimName: ccf228333faf5ae173ecc9df3001ce81b47901d9452e188577533170f1efa8d0

