# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-10-27T16:13:06Z"
  labels:
    app: simplebank
  name: simplebank
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: POSTGRES_DB
      value: bankdb
    image: docker.io/library/postgres:latest
    name: postgres
    ports:
    - containerPort: 3000
      hostPort: 3000
  - args:
    - redis-server
    image: docker.io/library/redis:latest
    name: redis
  - image: localhost/simplebank-api:latest
    name: simplebank-api